### ISSUE TITLE
The tool is not working any more

### ISSUE THREAD

**Issue by RamiMak** [TheWaveWarden/aoe2-color-tool#1]
After the new age of empires 2 de update, all the color mods have stopped working including this software.
Now even though you get the color changed successfully, the color remains the same. This tool need to be tweaked to go with the new changes that recently took place.

**Comment by StepS-** [comment]
To fix this, the tool needs to be updated to include a **spritecolors.json** file in the palettes folder. Colors there will be in the float format. Current base file:
```
{
	"TeamColors": {
		"Gaia": { "FloatRGBA": { "r": 1.000, "g": 1.000, "b": 1.000, "a": 1.000 } },
		"Player 1": { "FloatRGBA": { "r": 0.000, "g": 0.000, "b": 1.000, "a": 1.000 } },
		"Player 2": { "FloatRGBA": { "r": 1.000, "g": 0.000, "b": 0.000, "a": 1.000 } },
		"Player 3": { "FloatRGBA": { "r": 0.000, "g": 0.663, "b": 0.106, "a": 1.000 } },
		"Player 4": { "FloatRGBA": { "r": 0.839, "g": 0.839, "b": 0.106, "a": 1.000 } },
		"Player 8": { "FloatRGBA": { "r": 1.000, "g": 0.573, "b": 0.020, "a": 1.000 } },
		"Player 5": { "FloatRGBA": { "r": 0.482, "g": 0.937, "b": 0.941, "a": 1.000 } },
		"Player 6": { "FloatRGBA": { "r": 0.541, "g": 0.075, "b": 0.969, "a": 1.000 } },
		"Player 7": { "FloatRGBA": { "r": 0.400, "g": 0.400, "b": 0.400, "a": 1.000 } }
	},
	"OutlineColors": {
		"Gaia": { "FloatRGBA": { "r": 1.000, "g": 1.000, "b": 1.000, "a": 1.000 } },
		"Player 1": { "FloatRGBA": { "r": 0.000, "g": 0.000, "b": 1.000, "a": 1.000 } },
		"Player 2": { "FloatRGBA": { "r": 1.000, "g": 0.000, "b": 0.000, "a": 1.000 } },
		"Player 3": { "FloatRGBA": { "r": 0.016, "g": 0.647, "b": 0.078, "a": 1.000 } },
		"Player 4": { "FloatRGBA": { "r": 0.843, "g": 0.843, "b": 0.118, "a": 1.000 } },
		"Player 8": { "FloatRGBA": { "r": 1.000, "g": 0.588, "b": 0.020, "a": 1.000 } },
		"Player 5": { "FloatRGBA": { "r": 0.494, "g": 0.949, "b": 0.882, "a": 1.000 } },
		"Player 6": { "FloatRGBA": { "r": 0.588, "g": 0.059, "b": 0.980, "a": 1.000 } },
		"Player 7": { "FloatRGBA": { "r": 0.388, "g": 0.404, "b": 0.439, "a": 1.000 } }
	}
}
```
You should still keep producing the old .pal files if you want colors to also be modded in custom mods that still use SMX graphics.

**Comment by TyAshley** [comment]
So I'll need to place a spritecolors.json in this directory? C:\Program Files (x86)\Steam\steamapps\common\AoE2DE\Tools_Builds\Sprites\_palettes

**Comment by RoyalForgotten** [comment]
This tool always worked for me tbh

**Comment by TheWaveWarden** [comment]
@RamiMak @StepS- sorry guys, it's been almost two years!

I just fixed the tool (@StepS- many thanks for the needed info!), did a lot of improvements and pushed the latest version to the [release page](https://github.com/TheWaveWarden/aoe2-color-tool/releases). If you could verify the update works on your end I will post it to the forums and reddit. :)

**Comment by TheWaveWarden** [comment]
It seems the tool is working for other people as well. Closing this now.
